#ifndef MALLISERIALPORTDLL_GLOBAL_H
#define MALLISERIALPORTDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MALLISERIALPORTDLL_LIBRARY)
#  define MALLISERIALPORTDLL_EXPORT Q_DECL_EXPORT
#else
#  define MALLISERIALPORTDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // MALLISERIALPORTDLL_GLOBAL_H
